### PR TITLE
Provide preconfigured dev-environment and automated tests

### PR DESCRIPTION
**Pull request by papauorg**
Original PR was this: avollkopf/craftbeerpi4#44. Moved here to also include the latest changes.

This PR contains changes that enable a preconfigured development environment. It's using docker and devcontainers in visual studio code. With that it's easy for new contributors to get started or for the already active contributors to have a commonly configured environment that can be shared with others.

I mainly did this because whenever I want to check something I developed I built a docker container and ran it instead of starting it in vscode while developing. I don't need or want to install python in several versions on my "real" machine. So developing in a container provides a disposable environment that I can completely wipe or recreate as needed.

The devcontainer __can__ be used, but is completely optional. It's still possible to develop cbpi the same way as before and without devcontainers.

More info about devcontainers:
https://code.visualstudio.com/docs/remote/create-dev-container

### Features

- Preinstalled python 3.9
- Preinstalled dependencies (`requirements.txt`)
- Preinstalled craftbeerpi UI plugin in the current version
- MQTT Broker is automatically started with the dev environment
- MQTT Explorer is automatically started with the dev environment
- Preconfigured CBPI config directory (specific for the dev environment)
- Working Debugging support in vscode
- Test runner support in vscode
- Automated tests were fixed and are now running when an automated build is run in github
- Very short description in the readme on how easily get started with developing

The default configuration for the development environment can be extended as necessary. E.g. by adding a default dashboard or already configured hardware (MQTT Actors or similar).

#### Prerequisites
What's needed to use dev containers?
- docker
- visual studio code (with remote-containers extension)

Everything else is provided by the dev-container.

### Changes
The PR got bigger than expected, but there were a few things that needed to be changed in order to get the tests running and provide a distinct configuration specifically for the development environment.

#### Dev Container configuration
There is a new folder `.devcontainer` in the root directory of the project. This contains the configuration of the environment that should be started, when using the feature. It also contains a `cbpi-dev-config` folder that contains the configuration for craftbeerpi that should be used within the development environment.

#### Specifying an alternative configuration directory
Because the development environment as well as the automated tests need different configuration directorys to avoid interfering with the default config (or providing preconfigured values) the `cli.py` was updated. It's now possible to provide an additional option when starting cbpi. This new option is not required and the default is to fallback to the currently used `./config` directory.

Sample call:
```bash
cbpi --config-folder-path=./other-config-path start
```

The `cli.py` and other files that were using the `./config` directory hardcoded, were changed to now use a new class that abstracts away the location of the configuration (`configFolder.py`).  Some methods moved from `cli.py`to `configFolder.py`.

#### Fix tests
I also wanted to be able to run the tests in the vscode test runner and also include them in the automated build process. But many of the tests were failing due to different reasons. Some tests didn't make sense at all or were calling http endpoints that don't exist or similar. I guess they are very old and have not been run for a long time. So I made some fixes to the tests to be able to run most of them again. Also they now use their own, test-specific, configuration directory, thanks to the new config parameter feature.

#### Deleted craftbeerpi.db
I didn't find any code part, that was using the craftbeerpi.db. So I removed the files from the config directories.

### Screenshots
image
image
image
image

I did the entire development for this PR within the devcontainer and it works great. Looking forward to hear what you think. 

Best regards,
Philipp

### CODE REVIEW

**Comment by hurra** [comment]
Can this be merged please?

**Comment by avollkopf** [comment]
I need to get used to the environment to test it. However, I was now able to install everything and get my PC ready for Docker... 

I am now also able to start cbpi. One thing I noticed is the ui that is pulled via the dockerfile in .evcontainer:

It still points to my fork and should be changed to the upstream branch of the user interface:

`curl https://github.com/craftbeerpi/craftbeerpi4-ui/archive/main.zip`

**Comment by papauorg** [comment]
> It still points to my fork and should be changed to the upstream branch of the user interface:
> 
> `curl https://github.com/craftbeerpi/craftbeerpi4-ui/archive/main.zip`

I updated the URL in the Dockerfile

> I need to get used to the environment to test it. However, I was now able to install everything and get my PC ready for Docker...

Just let me know if you have any questions about that.

**Comment by avollkopf** [comment]
> Just let me know if you have any questions about that.

I will test a bit over the weekend, but I managed to install/start cbpi from your cloned fork. If I don't see any issues, I will merge that to the development branch for further testing.

**Comment by avollkopf** [comment]
@papauorg How is your workflow? I assume you need to install cbpi somehow in your container. 

- I installed the server with `pip install -e .` from inside the workspace folder
- I started cbpi with `cbpi --config-folder-path=.devcontainer/cbpi-dev-config start`

Now I can access the server and the mqttexplorer and so far everything seems to be working.
When I add a dummysensor, it'll also send updates to the mqttexplorer. However, no data will be generated.

The problem seems to be related to the fact that I did not run cbpi setup as I was using the alternative config folder, which causes an issue as no log folder is existing (since I did not create a log folder via cbpi setup).

-> Do I need to run cbpi setup to create a config and log folder and can use a different config during start or should the log folder be also located somewhere around the alternative config folder?

**Comment by avollkopf** [comment]
.. and the fermentation cotroller requires also an update. I can also look into that:

```
    def check_fermenter_file(self):
        if os.path.exists(self.cbpi.config_folder.get_file_path("fermenter_data.json")) is False:
            logging.info("INIT fermenter_data.json file")
            data = {
                    "data": [
                            ]
                    }
            destfile = self.cbpi.config_folder.get_file_path("fermenter_data.json")
            json.dump(data,open(destfile,'w'),indent=4, sort_keys=True)
        
        pathlib.Path(os.path.join(".", 'config/fermenterrecipes')).mkdir(parents=True, exist_ok=True)
```

The last line has the config path still hardcoded as it was added after your changes. Not sure, if I have added some other parts with fixed config folder for the fermenter recipes. I need to look into that.

**Comment by papauorg** [comment]
> @papauorg How is your workflow? I assume you need to install cbpi somehow in your container.

The way I'd do it is:
- Clone the repository (if not already done)
- Open VisualStudio Code in the main folder
- Use the "Reopen in Container" command by clicking here: 
image
- After that to run cbpi I'd just press `F5` to execute the debug task and let it run this way.
- If this has been done before it might be necessary to run `Rebuild Container` command. This would be necessary e.g. if the dependencies change. Those will be automatically installed when building a container.

> If I don't see any issues, I will merge that to the development branch for further testing.

This would have been the better target branch for this PR but there was no development branch when I created it.



> * I installed the server with `pip install -e .` from inside the workspace folder

There should be no need to explicitly install the server, as the configuration for cbpi is part of the development environment. It might be necessary to update the config when new features require new config files or the schema of a config file changes.

The config for the dev environment is intended to provide a preconfigured cbpi to easily get started and maybe easily test the most common functionality (e.g. some dummy sensors on a dashboard or similar). 

> -> Do I need to run cbpi setup to create a config and log folder and can use a different config during start or should the log folder be also located somewhere around the alternative config folder?

It might be a good idea to have the same behaviour for the log folder as for the config folder. Currently the log behavior should be the same as before because the log folder was not part of the config folder before and is not part of it after the change - at least as far as I see it. Maybe the startup logic of cbpi should simply create the log folder if it doesn't exist, yet? Would that solve your problem?

> .. and the fermentation cotroller requires also an update. I can also look into that:

I can have a look into that in this branch. I guess this is because the fermentation_controller was developed in parallel with this branch and I didn't replace the parts for the new feature, yet. Good catch!

Thanks for your feedback. I'll update the branch as soon as I had the time to make the fixes.

**Comment by avollkopf** [comment]
@papauorg I will wait for your changes with respect to the fermentation (recipe) controller. Once this is done, I will clone the repo again from scratch and try to start it as described above.

On the log folder, I just noticed that when I was adding a dummy sensor. When I did run cbpi setup and the log folder was available, the dummy sensors where working as expected.

I nned to think about the log folder creation, but most likely it is better that cbpi does not create it automatically and independent from the config folder as both folders are required in the same directory (at least for standard users). Otherwise, cbpi would create a log folder in every directory you try to start it.

But I need to get more familiar with this dev environment stuff (I even had to access my bios settings after XX years to get docker up and running :-) )

**Comment by avollkopf** [comment]
The changes in fermenter related controllers have some bugs. I will dig into the details and fix them. We just need the uuid in this case and not the full path. 

One example is loading a recipe from the recipe book:
It should look like:
http://192.168.163.67:8000/cbpi_ui/static/index.html#/fermenterrecipe/nTFQYzuCmzf44jyBdHB6rV

But it looks like:
`http://localhost:8001/cbpi_ui/static/index.html#/fermenterrecipe/./.devcontainer/cbpi-dev-config/fermenterrecipes/Cpapu9orAHzqMjhyM34g6g.yaml`

Everything else looks fine so far and I figured also out that I can start everything with F5 😄 

I will merge the change to the development branch and fix the fermenter recipe related issues

**Comment by avollkopf** [comment]
Issues with fermenter recipes should have been fixed now with this merge: https://github.com/craftbeerpi/craftbeerpi4/commit/fec02047adad26ed41f058ac60e04f9a17d4e58a

**Comment by papauorg** [comment]
@avollkopf Ahh, yes, I didn't change that correctly. My fault. Sorry and thanks for the fix.

**Comment by avollkopf** [comment]
@papauorg I started further development on the server with respect to the fermenter. However, for this purpose I need to work in parallel on the ui and update the dev branch here as well. From that point of view, I need to change the UI to dev in the dev environment dockerfile. We can revert that back at a later point of time, if required.

**Pull request merged**
