### PR TITLE
Support beerxml , kbh database upload and brewfather import

### PR DESCRIPTION
**Pull request by avollkopf**
This commit allows to upload beerxml and kbh files directly from the cbpi4ui to an upload folder.

Currently, an additional plugin is required to create a cbpi recipe from those files / the database. In a next step, better support for recipe creation has to be done.

This changes requires also the change of the cbpiui: https://github.com/Manuel83/craftbeerpi4-ui/pull/4

### CODE REVIEW

**Comment by avollkopf** [comment]
For the latest functions, an update of the UI is also required: https://github.com/Manuel83/craftbeerpi4-ui/pull/4/commits/1e4ef0daa44f1c43eec761c567527a0a1abb77b8

**Comment by hurra** [comment]
craftbeerpi4boot should be implement as a systemd service file

**Comment by avollkopf** [comment]
> 
> 
> craftbeerpi4boot should be implement as a systemd service file

I just included it here as I am using it currently with my test system. I hve no intention to use it permanently. If you have a corresponding file, feel free to add it via pull request, I could also add it via my fork. I think it needs to be sorted out anyhow on how cbpi is installed, configured,... once cbpi4 is ready for production.

**Comment by avollkopf** [comment]
Added also Brewfather web app support to import recipes directly to cbpi4. API key and user id need to be entered in cbpi settings

Screenshot 2021-06-13 200118

**Pull request closed without merging**
